[tool.poetry]
name = "electricmeters"
version = "0.11.1-rc1"
description = ""
authors = ["Vladislav Trofimenko <foss@slashfast.dev>"]
license = 'MIT'

[tool.poetry.dependencies]
python = ">=3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
