[tool.poetry]
name = "electricmeters"
version = "0.2.0-rc2"
description = ""
authors = ["Vladislav Trofimenko <foss@slashfast.dev>"]

[tool.poetry.dependencies]
python = ">=3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
