# Название счетчика
brand = "mercury"

# Модель счетчика
model = "236"

# шаблон запроса (либо пустая строка, либо 'read_energy')
# response_template = ""
# отсутствие параметра равно ""
response_template = "read_energy"

# выводить сообщения для отладки
debug = false

# Числовой эквивалент приставок СИ
# отсутствие параметра равно 1
# некорректные числовые значения будут проигнорированы
metric_prefix = 1000

# Первый преобразователь
[[converters]]

# IP преобразователя RS485-TCP/IP
ip = "10.0.0.101"

# Порт преобразователя RS485-TCP/IP
port = 19

# Первый счетчик первого преобразователя
[[converters.meters]]

# Сетевой адрес счетчика
address = 5

# Уровень доступа
access_level = 2

# Пароль строго 6 байт (1 символ – 1 байт)
password = "222222"

# Пример полезной нагрузки запроса показаний счетчика от сброса по сумме тарифов:
# [0x05, 0x00, 0x01, 0x00] (то же, что [5, 0, 1, 0])
# где:
#     0x05 – номер запроса
#     0x00 – номер массива
#     0x01 – номер месяца (оставьте любое целочисленное значение 0 <= x <= 255, если в запросе не требуется)
#     0x00 – номер тарифа (значение 0 явялется суммой тарифов)
# Полезная нагрузка состоит из последовательности байтов
# Возможные значения смотрите в документации
payload = [0x05, 0x00, 0x01, 0x00]

# Второй счетчик первого преобразователя
[[converters.meters]]
address = 19
access_level = 2
password = "222222"
payload = [0x05, 0x00, 0x01, 0x00]

# Второй преобразователь
[[converters]]
ip = "10.0.0.101"
port = 19

[[converters.meters]]
address = 5
access_level = 2
password = "222222"
payload = [0x05, 0x00, 0x01, 0x00]

[[converters.meters]]
address = 5
access_level = 2
password = "222222"
payload = [0x05, 0x00, 0x01, 0x00]